#!/bin/bash
N=$((5*$1))
IP=$2
exonum-cryptocurrency-advanced finalize --public-api-address $IP:8200 --private-api-address $IP:8091 example/$(($N-4))/sec.toml example/$(($N-4))/node.toml --public-configs example/1/pub.toml example/2/pub.toml example/3/pub.toml example/4/pub.toml example/5/pub.toml example/6/pub.toml example/7/pub.toml example/8/pub.toml example/9/pub.toml example/10/pub.toml example/11/pub.toml example/12/pub.toml example/13/pub.toml example/14/pub.toml example/15/pub.toml example/16/pub.toml example/17/pub.toml example/18/pub.toml example/19/pub.toml example/20/pub.toml example/21/pub.toml example/22/pub.toml example/23/pub.toml example/24/pub.toml example/25/pub.toml
exonum-cryptocurrency-advanced finalize --public-api-address $IP:8201 --private-api-address $IP:8092 example/$(($N-3))/sec.toml example/$(($N-3))/node.toml --public-configs example/1/pub.toml example/2/pub.toml example/3/pub.toml example/4/pub.toml example/5/pub.toml example/6/pub.toml example/7/pub.toml example/8/pub.toml example/9/pub.toml example/10/pub.toml example/11/pub.toml example/12/pub.toml example/13/pub.toml example/14/pub.toml example/15/pub.toml example/16/pub.toml example/17/pub.toml example/18/pub.toml example/19/pub.toml example/20/pub.toml example/21/pub.toml example/22/pub.toml example/23/pub.toml example/24/pub.toml example/25/pub.toml
exonum-cryptocurrency-advanced finalize --public-api-address $IP:8202 --private-api-address $IP:8093 example/$(($N-2))/sec.toml example/$(($N-2))/node.toml --public-configs example/1/pub.toml example/2/pub.toml example/3/pub.toml example/4/pub.toml example/5/pub.toml example/6/pub.toml example/7/pub.toml example/8/pub.toml example/9/pub.toml example/10/pub.toml example/11/pub.toml example/12/pub.toml example/13/pub.toml example/14/pub.toml example/15/pub.toml example/16/pub.toml example/17/pub.toml example/18/pub.toml example/19/pub.toml example/20/pub.toml example/21/pub.toml example/22/pub.toml example/23/pub.toml example/24/pub.toml example/25/pub.toml
exonum-cryptocurrency-advanced finalize --public-api-address $IP:8203 --private-api-address $IP:8094 example/$(($N-1))/sec.toml example/$(($N-1))/node.toml --public-configs example/1/pub.toml example/2/pub.toml example/3/pub.toml example/4/pub.toml example/5/pub.toml example/6/pub.toml example/7/pub.toml example/8/pub.toml example/9/pub.toml example/10/pub.toml example/11/pub.toml example/12/pub.toml example/13/pub.toml example/14/pub.toml example/15/pub.toml example/16/pub.toml example/17/pub.toml example/18/pub.toml example/19/pub.toml example/20/pub.toml example/21/pub.toml example/22/pub.toml example/23/pub.toml example/24/pub.toml example/25/pub.toml
exonum-cryptocurrency-advanced finalize --public-api-address $IP:8204 --private-api-address $IP:8095 example/$N/sec.toml example/$N/node.toml --public-configs example/1/pub.toml example/2/pub.toml example/3/pub.toml example/4/pub.toml example/5/pub.toml example/6/pub.toml example/7/pub.toml example/8/pub.toml example/9/pub.toml example/10/pub.toml example/11/pub.toml example/12/pub.toml example/13/pub.toml example/14/pub.toml example/15/pub.toml example/16/pub.toml example/17/pub.toml example/18/pub.toml example/19/pub.toml example/20/pub.toml example/21/pub.toml example/22/pub.toml example/23/pub.toml example/24/pub.toml example/25/pub.toml

 